# Site settings
title: Oceanhackweek 2019
email: oceanhkw@uw.edu
description: Data Science + Oceanography <br>
             University of Washington <br>
             Aug. 19 - 23, 2019 <br> <br>
             Applications will be accepted soon! <br> 
             

# Banner button to lead to form, then schedule, then next year's website.
banner_button_url: https://oceanhackweek.github.io/ohw2018/
banner_button_text: Oceanhackweek 2018


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/oceanhackweek
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://oceanhackweek2018.slack.com
twitter_url:
email_url: oceanhkw@uw.edu

# Build settings
markdown: kramdown

# Submodule setting
destination:  _site/
plugins_dir:  jekyll-spectral-theme/_plugins/
layouts_dir:  jekyll-spectral-theme/_layouts/
includes_dir: jekyll-spectral-theme/_includes/
exclude:
- jekyll-spectral-theme/

include: ["_pages"]
