name: ohw-site
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.9
  # website/blog building
  - myst-nb>=0.16.0
  - sphinx>= 5.0.2
  - jupytext
  - pre-commit
  # - sphinx-panels
  - ablog>=0.10.26
  - sphinx-autobuild>=2021.3.14
  - pydata-sphinx-theme>=0.9.0
  - ipywidgets>=7.7.1
  - sphinx-design>=0.2.0
  # computation
  - numpy>=1.23.1
  - pandas>=1.4.3
  - xarray>=2022.3.0
